apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/project: jaeger
    app.kubernetes.io/name: devops
spec:
  # 实例数量
  #  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/project: devops
      app.kubernetes.io/name: salt
  template:
    metadata:
      labels:
        app.kubernetes.io/project: devops
        app.kubernetes.io/name: salt
    spec:
      containers:
        - name: devops-salt
          # 镜像
          image: docker-images
          # 拉取策略： Always 避免使用了相同得镜像版本导致重新发布后仍使用了旧版的镜像
          #           IfNotPresent: 如果镜像已经存在，直接复用
          imagePullPolicy: Always
          # 环境变量声明
          env:
            - name: SPAN_STORAGE_TYPE
              value: aliyun-log
          # 声明服务端口
          ports:
            - containerPort: 65233
              protocol: UDP
            - containerPort: 80
          resources:
            # cpu和内存的最大值
            limits:
              cpu: 1
              memory: 2Gi
            # cpu和内存的最小值
            requests:
              cpu: 100m
              memory: 128Mi
